branch-defaults:
  master:
    environment: null
    group_suffix: null
global:
  application_name: socialdistance
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Python 3.8 running on 64bit Amazon Linux 2
  default_region: us-west-2
  include_git_submodules: false
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: local
  workspace_type: Application
